### ISSUE TITLE
"make agent" did not create a container

### ISSUE THREAD

**Issue by xcheng75** [open-telemetry/opentelemetry-ebpf-profiler#152]
followed the root folder README.md, build agent image, but "make agent" command did not create a running container.

**Comment by florianl** [comment]
hi @xcheng75 
the command `make agent` just builds an executable and is not intended to create a running container. As described, `make docker-image` provides the build environment for `make agent` to run and build the executable. Hope this helps?

**Comment by xcheng75** [comment]
I have a MacOs machine, i guess i need to create a docker container in linux vm. i was hoping to see some document or instructions to help me on it.

**Comment by xcheng75** [comment]
> hi @xcheng75 the command `make agent` just builds an executable and is not intended to create a running container. As described, `make docker-image` provides the build environment for `make agent` to run and build the executable. Hope this helps?

Make agent is building a image. Are you saying i need to create a container from the image and execute "make agent"?

**Comment by xcheng75** [comment]
i followed devfiler "Adding data" link to download ARM64 and unzipped file, did 
sudo ./pf-host-agent -project-id=123 -secret-token=123 -collection-agent=127.0.0.1:11000 -disable-tls 
but got "./pf-host-agent: ./pf-host-agent: cannot execute binary file"
Any idea why is not working?

**Comment by florianl** [comment]
hi @xcheng75 

While the visualization tool, devfiler, can run on macOS and Linux, the OTel eBPF Profiler will run **only** on Linux systems. The OTel eBPF profiler does no support for macOS or Windows at the moment.

Following the [Building instructions](https://github.com/open-telemetry/opentelemetry-ebpf-profiler?tab=readme-ov-file#building), with `make docker-image` an environment (docker image) is created, that is needed in the next step for `make agent`. `make agent` uses this environment (docker image) to build an executable. This resulting executable is named `otel-profiling-agent`.

It looks like the instructions for `devfiler` still reference `pf-host-agent`. This is not correct and should be updated. Instead `sudo ./otel-profiling-agent -collection-agent=127.0.0.1:11000 -disable-tls` should be used to run the OTel eBPF profiler and send its data to `devfiler`.

**Comment by xcheng75** [comment]
> hi @xcheng75
> 
> While the visualization tool, devfiler, can run on macOS and Linux, the OTel eBPF Profiler will run **only** on Linux systems. The OTel eBPF profiler does no support for macOS or Windows at the moment.
> 
> Following the [Building instructions](https://github.com/open-telemetry/opentelemetry-ebpf-profiler?tab=readme-ov-file#building), with `make docker-image` an environment (docker image) is created, that is needed in the next step for `make agent`. `make agent` uses this environment (docker image) to build an executable. This resulting executable is named `otel-profiling-agent`.
> 
> It looks like the instructions for `devfiler` still reference `pf-host-agent`. This is not correct and should be updated. Instead `sudo ./otel-profiling-agent -collection-agent=127.0.0.1:11000 -disable-tls` should be used to run the OTel eBPF profiler and send its data to `devfiler`.

after i did "make agent", i got "opentelemetry-ebpf-profiler" executable in the repo root directory,
then i did "sudo ./opentelemetry-ebpf-profiler -collection-agent=127.0.0.1:11000 -disable-tls" i got:
./opentelemetry-ebpf-profiler: ./opentelemetry-ebpf-profiler: cannot execute binary file

**Comment by florianl** [comment]
hi @xcheng75

Can you please provide the output of the following commands in the environment where you want to run the profiling agent?

```
$ uname -r
$ file ./opentelemetry-ebpf-profiler
```

**Comment by rockdaboot** [comment]
@xcheng75
It looks like you are trying to run `./opentelemetry-ebpf-profiler` on MacOS (`23.6.0` indicates this). This won't work.
The profiler only runs on Linux. So you have to set up a virtual machine and run the profiler from within the VM.

**Comment by Annosha** [comment]
@rockdaboot Hi, I would like to make following changes to reflect in [Building guide](https://github.com/open-telemetry/opentelemetry-ebpf-profiler?tab=readme-ov-file#building) and open a PR. 

**Building**
**Quick Start**
If you'd like to quickly test the agent, you can skip to the "[Visualizing data locally](https://github.com/open-telemetry/opentelemetry-ebpf-profiler?tab=readme-ov-file#visualizing-data-locally)" section and launch devfiler. From there, follow the download links for prebuilt agent binaries.

**Platform Requirements**
The agent can be built with the provided make targets. Docker is required for containerized builds, and both amd64 and arm64 architectures are supported.

- For Linux, the following steps apply:

1. Build the Docker image containing the build environment:
`make docker-image`

2. Build the agent for your current machine's architecture:
`make agent`
3. To cross-compile for a different architecture (e.g., arm64):
`make agent TARGET_ARCH=arm64`

The resulting binary will be named `opentelemetry-ebpf-profiler` in the current directory.

**macOS**
Since the profiler is **Linux-only**, macOS users need to set up a Linux VM to build and run the agent. Ensure the appropriate architecture is specified if using cross-compilation. Use the same make targets as above after the Linux environment is configured in the VM.

**Alternative Build (Without Docker)**
You can build the agent without Docker by directly installing the dependencies listed in the Dockerfile. Once dependencies are set up, simply run:
`make`
This will build the profiler natively on your machine.

Please provide your feedback. Thanks.

**Comment by athre0z** [comment]
Thanks @Annosha, that sounds good! Please feel free to just create that PR so we can comment and iterate on it more comfortably! :) This also reminds me that we currently don't have linked to pre-built artifacts in devfiler anymore. I suppose we might have to remove the quick-start section until we publish binary releases on this repository.

**Comment by Annosha** [comment]
@athre0zI was trying to set up the development environment on my local machine, and there seemed to be insufficient information on how to do it in the CONTRIBUTING.md file. After cloning repo I ran `make test` commands that was given in sequence. 
![go](https://github.com/user-attachments/assets/0b0b0786-a353-4644-80bb-0ea4fa5c8bf1)

**Comment by rockdaboot** [comment]
@Annosha There is indeed no list of required tooling, and we should have one.

For now, you can see the required tools listed in the `Dockerfile`, which mostly is `wget make git clang-16 golang unzip`. The tools for cross-building likely isn't required in your case.
